(() => {
  'use strict';

  const STORE = 'bdr.money.app.v12';
  const LEGACY = ['bdr.money.app.v11','bdr.money.app.v10','bdr.money.app.v9','bdr.money.app.v8','bdr.money.app.v7','bdr.money.app.v6','bdr.money.app.v5','bdr.money.app.v4','bdr.money.app.v3'];

  const incomeCats = ['Зарплата','Стипендия','Проценты и бонусы','Поступления от людей','Пополнение наличными','Прочие доходы','Ипотека/жильё: справочно','Не учитывается'];
  const expenseCats = ['Продукты и супермаркеты','Маркетплейсы/покупки','Доставка/Еда вне дома','Транспорт','Связь, интернет, подписки','ЖКХ/квартплата','Здоровье, аптеки и уход','Услуги/комиссии','Страхование','Наличные','Переводы другим людям','Кредиты/ипотека','Ремонт/дом','Крупные разовые расходы','Прочие расходы','Не учитывается'];
  const cats = [...new Set([...incomeCats, ...expenseCats])];
  const dirs = ['Доход','Расход','Возврат','Справочно','Внутренний перевод','Техническая операция'];
  const stable = ['Зарплата','Стипендия','Проценты и бонусы'];
  const incomeReal = ['Зарплата','Стипендия','Проценты и бонусы','Поступления от людей','Прочие доходы'];
  const routine = ['Продукты и супермаркеты','Маркетплейсы/покупки','Доставка/Еда вне дома','Транспорт','Связь, интернет, подписки','Здоровье, аптеки и уход','Услуги/комиссии','Страхование','Наличные','Ремонт/дом','Прочие расходы'];
  const credit = ['Кредиты/ипотека','Ипотека/жильё: справочно'];
  const palette = ['#111111','#c8a96a','#6d5b3f','#087f5b','#2454ff','#7c3aed','#b42318','#f59e0b','#475569','#0f766e','#9333ea'];

  let activeTab = 'dashboard';
  let selectedExpense = null;
  let selectedIncome = null;
  let dashboardMode = localStorage.getItem('bdr.dashboard.mode') || 'total';
  let pendingImport = null;
  let state = loadState();

  function uid(){ return (window.crypto && crypto.randomUUID) ? crypto.randomUUID() : 'id_' + Date.now() + '_' + Math.random().toString(16).slice(2); }
  function money(v){ return new Intl.NumberFormat('ru-RU', { style:'currency', currency:'RUB', maximumFractionDigits:0 }).format(Number(v) || 0); }
  function num(v){ if(typeof v === 'number') return v; if(v == null) return 0; return Number(String(v).replace(/\s| /g,'').replace(',', '.').replace(/[₽р]/gi,'')) || 0; }
  function abs(v){ return Math.abs(num(v)); }
  function clean(v){ return String(v == null ? '' : v).toLowerCase().replace(/ё/g,'е').replace(/\s+/g,' ').trim(); }
  function esc(v){ return String(v == null ? '' : v).replace(/[&<>"]/g, ch => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[ch])); }
  function asBool(v, def=true){ if(v === undefined || v === null || v === '') return def; const s = clean(v); if(['нет','false','0','no','n'].includes(s)) return false; if(['да','true','1','yes','y'].includes(s)) return true; return Boolean(v); }
  function repairDate(v){ const s = String(v || '').trim(); const m = s.match(/^(\d{4})-(\d{2})-(\d{2})/); if(!m) return s; let y = Number(m[1]); const cur = new Date().getFullYear(); if(y !== cur && ['03','04','05','06'].includes(m[2])) y = cur; return `${y}-${m[2]}-${m[3]}`; }
  function toDate(v){
    if(!v) return '';
    if(v instanceof Date && !isNaN(v)) return repairDate(v.toISOString().slice(0,10));
    if(typeof v === 'number' && window.XLSX && XLSX.SSF && XLSX.SSF.parse_date_code){ const d = XLSX.SSF.parse_date_code(v); if(d) return repairDate(`${d.y}-${String(d.m).padStart(2,'0')}-${String(d.d).padStart(2,'0')}`); }
    const s = String(v).trim();
    const m = s.match(/(\d{1,2})[.\/\-](\d{1,2})[.\/\-](\d{2,4})/);
    if(m){ const y = m[3].length === 2 ? '20' + m[3] : m[3]; return repairDate(`${y}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`); }
    const d = new Date(s); return isNaN(d) ? repairDate(s.slice(0,10)) : repairDate(d.toISOString().slice(0,10));
  }
  function showDate(v){ const d = toDate(v); const m = d.match(/^(\d{4})-(\d{2})-(\d{2})/); return m ? `${m[3]}.${m[2]}.${m[1].slice(2)}` : (d || '—'); }
  function monthOf(v){ const d = toDate(v); return /^\d{4}-\d{2}/.test(d) ? d.slice(0,7) : 'Без месяца'; }

  function baseRules(){ return [
    rule('ПИМУ → Стипендия','contains','пиму','Стипендия','Доход',true,100),
    rule('Парацельс → Зарплата','contains','парацельс','Зарплата','Доход',true,100),
    rule('Аквимекс → Зарплата','contains','аквимекс','Зарплата','Доход',true,100),
    rule('EPR GIS ZKH → ЖКХ','contains','epr_gis_zkh','ЖКХ/квартплата','Расход',true,100),
    rule('Ипотека → справочно','regex','ипотек|первоначальн|первоначальный взнос|кредитные средства|выдача кредита|зачисление кредита|лицевой счет|эскроу|дду|жилье|жильё|квартира','Ипотека/жильё: справочно','Справочно',false,250)
  ]; }
  function rule(name, type, pattern, category, direction, includeTotals, priority=50){ return { id:uid(), enabled:true, name, matchType:type, pattern, category, direction, includeTotals, priority }; }
  function loadState(){
    const embedded = Array.isArray(window.operations) ? window.operations.map(normalizeOp) : [];
    for(const k of [STORE, ...LEGACY]){ try{ const saved = JSON.parse(localStorage.getItem(k)); if(saved && Array.isArray(saved.operations)) return hydrate(saved, embedded); }catch(e){} }
    return hydrate({ operations: embedded, rules: baseRules(), imports: [], settings: { minSavings:0 } }, embedded);
  }
  function hydrate(s, embedded){ s.operations = (s.operations || []).map(normalizeOp); if(!s.operations.length && embedded.length) s.operations = embedded; s.rules = (s.rules || baseRules()).map((r,i)=>Object.assign({enabled:true, priority:50+i}, r)); s.imports = s.imports || []; s.settings = Object.assign({minSavings:0}, s.settings || {}); normalizeAll(s); return s; }
  function save(){ localStorage.setItem(STORE, JSON.stringify(state)); }
  function normalizeOp(raw){ raw = raw || {}; const amount = num(raw.amount ?? raw['Сумма'] ?? raw.sum); const d = toDate(raw.date ?? raw['Дата']); return { id: raw.id || raw.ID || raw['ID'] || uid(), importKey: raw.importKey || '', date: d, month: raw.month || raw['Месяц'] || monthOf(d), bank: raw.bank || raw['Банк'] || '', sourceType: raw.sourceType || raw['Тип исходный'] || raw['Источник'] || '', bankCategory: raw.bankCategory || raw['Категория банка'] || '', category: raw.category || raw['Категория учета'] || raw['Группа БДР'] || 'Прочие расходы', direction: raw.direction || raw['Направление'] || (amount >= 0 ? 'Доход' : 'Расход'), amount, includeTotals: asBool(raw.includeTotals ?? raw['Учет_БДР'] ?? raw['Включать в общие итоги?'], true), description: raw.description || raw['Описание'] || '', account: raw.account || raw['Счет/карта'] || raw['Счёт/карта'] || '', block: raw.block || raw['Блок учета'] || '', manuallyEdited: Boolean(raw.manuallyEdited) }; }
  function isMortgage(op){ const t = clean([op.description, op.bankCategory, op.sourceType, op.category, op.block, op.account].join(' ')); return /ипотек|первоначальн|первоначальный взнос|кредитные средства|выдача кредита|зачисление кредита|лицевой счет|лицевой сч|эскроу|дду|жилье|жильё|квартира/.test(t) || (num(op.amount) > 1000000 && /(банк|зачисл|поступл|перевод|кредит)/.test(t)); }
  function normalizeAll(s){ (s.operations || []).forEach(op => { op.date = repairDate(op.date); op.month = monthOf(op.date); if(isMortgage(op) || credit.includes(op.category)){ if(isMortgage(op)) op.category = 'Ипотека/жильё: справочно'; op.direction = op.category === 'Кредиты/ипотека' ? 'Расход' : 'Справочно'; op.includeTotals = false; op.block = 'Кредиты'; } }); }
  function setOp(op, cat, dir, inc, block){ op.category = cat; op.direction = dir; op.includeTotals = inc; op.block = block || (!inc ? 'Исключено' : dir === 'Доход' ? 'Доходы' : dir === 'Справочно' ? 'Справочно' : cat === 'ЖКХ/квартплата' ? 'Обязательные платежи' : 'Расходы'); return op; }
  function matchRule(text, r){ try{ return r.matchType === 'regex' ? new RegExp(r.pattern, 'i').test(text) : text.includes(clean(r.pattern)); }catch(e){ return text.includes(clean(r.pattern)); } }
  function classify(op, force=false){ if(op.manuallyEdited && !force) return op; const t = clean([op.description, op.bankCategory, op.sourceType, op.bank, op.account].join(' ')); if(isMortgage(op)) return setOp(op,'Ипотека/жильё: справочно','Справочно',false,'Кредиты'); if(abs(op.amount) === 1 && /(магнит|доставка|провер|тест)/.test(t)) return setOp(op,'Не учитывается','Техническая операция',false); if(/(сергей к|сергей николаевич|между своими|своей карты|своего счета|пополнение своей|перевод между|сбер.*т.?банк|т.?банк.*сбер)/.test(t)) return setOp(op,'Не учитывается','Внутренний перевод',false); const r = state.rules.filter(x=>x.enabled).sort((a,b)=>(b.priority||0)-(a.priority||0)).find(x=>matchRule(t,x)); if(r) return setOp(op,r.category,r.direction,r.includeTotals); if(/внесение налич|пополнение налич|банкомат|atm/.test(t)) return setOp(op,'Пополнение наличными','Справочно',false); if(/ипотек|погашение кредита|кредит/.test(t) && op.amount < 0) return setOp(op,'Кредиты/ипотека','Расход',false,'Кредиты'); if(/возврат|refund|отмена/.test(t) || (op.amount > 0 && /расход/.test(clean(op.sourceType)))) return setOp(op,mapExpense(t),'Возврат',true); if(op.amount >= 0) return setOp(op,mapIncome(t),'Доход',true); return setOp(op,mapExpense(t),'Расход',true); }
  function mapIncome(t){ if(/зарплат|аванс/.test(t)) return 'Зарплата'; if(/стипенд|пиму/.test(t)) return 'Стипендия'; if(/кэшбэк|cashback|бонус|процент/.test(t)) return 'Проценты и бонусы'; if(/перевод|зачисление от/.test(t)) return 'Поступления от людей'; return 'Прочие доходы'; }
  function mapExpense(t){ if(/супермаркет|пятероч|магнит|перекресток|ашан|лента|продукт/.test(t)) return 'Продукты и супермаркеты'; if(/wildberries|ozon|маркет|marketplace/.test(t)) return 'Маркетплейсы/покупки'; if(/кафе|ресторан|доставка|еда|delivery|самокат|вкусно|burger|kfc|чио/.test(t)) return 'Доставка/Еда вне дома'; if(/такси|метро|транспорт|автобус|топливо|азс/.test(t)) return 'Транспорт'; if(/мтс|билайн|мегафон|tele2|интернет|подписк|apple|google|yandex plus|кинопоиск/.test(t)) return 'Связь, интернет, подписки'; if(/жкх|квартплат|epr_gis_zkh/.test(t)) return 'ЖКХ/квартплата'; if(/аптек|мед|клиник|стомат|космет|уход/.test(t)) return 'Здоровье, аптеки и уход'; if(/комисс|услуг|сервис/.test(t)) return 'Услуги/комиссии'; if(/страхов/.test(t)) return 'Страхование'; if(/налич|банкомат|atm/.test(t)) return 'Наличные'; if(/перевод/.test(t)) return 'Переводы другим людям'; if(/ремонт|дом|строй|леруа|мебел|hoff/.test(t)) return 'Ремонт/дом'; return 'Прочие расходы'; }
  function opKey(op){ return [op.date, Math.round(num(op.amount)*100)/100, clean(op.bank), clean(op.description), clean(op.account), clean(op.sourceType)].join('|'); }

  async function parseFiles(files){ if(!files || !files.length) throw new Error('Сначала выбери файл.'); let rows=[]; for(const file of files) rows = rows.concat(await parseFile(file)); rows = rows.map(x=>classify(x)); const existing = new Set(state.operations.map(x=>x.importKey || opKey(x))); const seen = new Set(); let dup=0, fresh=[]; rows.forEach(op=>{ op.importKey = opKey(op); if(existing.has(op.importKey) || seen.has(op.importKey)) dup++; else { seen.add(op.importKey); fresh.push(op); } }); return { files:[...files].map(f=>f.name), operations:fresh, duplicates:dup, stats:previewStats(fresh, dup) }; }
  async function parseFile(file){ const name=file.name.toLowerCase(); if(name.endsWith('.json')) return JSON.parse(await file.text()).map(normalizeOp); if(name.endsWith('.csv') || name.endsWith('.txt')) return parseCsv(await file.text(), name); if(!window.XLSX) throw new Error('Не загрузилась библиотека XLSX.'); const wb = XLSX.read(await file.arrayBuffer(), {type:'array',cellDates:true}); let out=[]; wb.SheetNames.forEach(sn=>{ out = out.concat(parseSheet(XLSX.utils.sheet_to_json(wb.Sheets[sn], {header:1,raw:false,defval:''}), name)); }); return out; }
  function parseCsv(text, name){ const sep = text.includes(';') ? ';' : text.includes('\t') ? '\t' : ','; const lines = text.split(/\r?\n/).filter(Boolean); const h = split(lines.shift(), sep); return lines.map(line=>rowToOp(Object.fromEntries(split(line,sep).map((v,i)=>[h[i] || 'col'+i, v])), name)).filter(Boolean); }
  function split(line, sep){ const out=[]; let cur='', q=false; for(const ch of line){ if(ch === '"'){ q=!q; continue; } if(ch === sep && !q){ out.push(cur); cur=''; continue; } cur += ch; } out.push(cur); return out; }
  function parseSheet(rows, name){ const hi = rows.findIndex(r=>{ const t = clean(r.join(' ')); return r.filter(Boolean).length >= 3 && ['дата','сумма','описан','операц','назнач','категор','карта','счет','счёт'].filter(w=>t.includes(w)).length >= 2; }); if(hi < 0) return []; const h = rows[hi].map(x=>String(x).trim()); return rows.slice(hi+1).map(r=>Object.fromEntries(h.map((k,i)=>[k,r[i]]))).map(o=>rowToOp(o,name)).filter(Boolean); }
  function val(obj, names){ const entries = Object.entries(obj); for(const nm of names){ const f = entries.find(([k])=>clean(k) === clean(nm) || clean(k).includes(clean(nm))); if(f) return f[1]; } return ''; }
  function rowToOp(obj, name){ const bank = /сбер|sber/.test(name) ? 'Сбер' : /тбанк|тинькофф|tinkoff|t-bank/.test(name) ? 'Т-Банк' : val(obj,['Банк']); const sourceType = /доход/.test(name) ? 'Доходы файл' : /расход/.test(name) ? 'Расходы файл' : val(obj,['Тип исходный','Источник']) || 'Банковская выгрузка'; const date = toDate(val(obj,['Дата','Дата операции','Дата платежа','Дата и время','date'])); const description = String(val(obj,['Описание','Назначение платежа','Операция','Детали операции','Контрагент','Получатель','Плательщик','Место операции','description']) || '').trim(); let amount = num(val(obj,['Сумма','Сумма операции','Сумма платежа','Сумма в валюте операции','amount','Приход','Расход'])); const inc = num(val(obj,['Приход','Зачисления','Поступления'])); const exp = num(val(obj,['Расход','Списания'])); if(inc) amount = Math.abs(inc); if(exp) amount = -Math.abs(exp); if(/расход/.test(name) && amount > 0) amount = -Math.abs(amount); if(/доход/.test(name) && amount < 0) amount = Math.abs(amount); if(!date && !description && !amount) return null; return normalizeOp({date, bank, sourceType, bankCategory:val(obj,['Категория','Категория банка']), category:val(obj,['Категория учета','Группа БДР']), direction:val(obj,['Направление','Тип потока']), amount, description, account:val(obj,['Счет','Счёт','Карта','Номер карты','Счет/карта','Счёт/карта']), includeTotals:val(obj,['Учет_БДР']) || undefined}); }
  function previewStats(rows, dup){ const s=summarize(rows); return { newRows:rows.length, duplicates:dup, excluded:rows.filter(o=>!o.includeTotals).length, review:rows.filter(o=>['Прочие расходы','Прочие доходы'].includes(o.category)).length, income:s.ordinaryIncome, expense:s.allSpending, credits:s.creditInfo, mortgage:s.mortgageInfo }; }

  function summarize(rows){ const s={ordinaryIncome:0,stableIncome:0,routine:0,zhkh:0,large:0,transfers:0,allSpending:0,creditInfo:0,mortgageInfo:0,byIncome:{},byRoutine:{}}; (rows || []).forEach(op=>{ const cat=op.category, amount=num(op.amount), aa=abs(amount), dir=op.direction; if(credit.includes(cat)){ if(cat==='Кредиты/ипотека') s.creditInfo += aa; else s.mortgageInfo += aa; return; } if(op.includeTotals === false || cat === 'Не учитывается' || aa <= 0.009) return; if(dir==='Доход'){ if(incomeReal.includes(cat)){ s.ordinaryIncome += amount; s.byIncome[cat]=(s.byIncome[cat]||0)+amount; } if(stable.includes(cat)) s.stableIncome += amount; } if(dir==='Расход'){ if(routine.includes(cat)){ s.routine += aa; s.byRoutine[cat]=(s.byRoutine[cat]||0)+aa; } if(cat==='ЖКХ/квартплата') s.zhkh += aa; if(cat==='Крупные разовые расходы') s.large += aa; if(cat==='Переводы другим людям') s.transfers += aa; } if(dir==='Возврат' && routine.includes(cat)){ s.routine -= aa; s.byRoutine[cat]=(s.byRoutine[cat]||0)-aa; } }); return s; }
  function months(){ const m = [...new Set(state.operations.map(o=>o.month).filter(x=>/^\d{4}-\d{2}$/.test(x)))].sort(); return m.length ? m : ['Нет данных']; }
  function rowsMonth(m){ return state.operations.filter(o=>m==='all' || o.month===m); }
  function table(h, rows, empty='Нет данных'){ if(!rows.length) return `<div class="empty">${empty}</div>`; return `<div class="scroll"><table><thead><tr>${h.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`; }
  function entries(obj){ return Object.entries(obj).filter(([,v])=>v > 0.009).sort((a,b)=>b[1]-a[1]).map(([category,value],i)=>({category,value,color:palette[i%palette.length]})); }
  function pie(list, selected, mode){ const total=list.reduce((z,x)=>z+x.value,0); if(!total) return '<div class="empty">Нет данных для диаграммы</div>'; let off=0; const circles=list.map(x=>{ const part=x.value/total*100, chosen=selected===x.category, dim=selected&&selected!==x.category, cur=off; off-=part; return `<circle data-chart-mode="${mode}" data-chart-cat="${esc(x.category)}" cx="90" cy="90" r="67" fill="none" stroke="${x.color}" stroke-width="${chosen?31:24}" pathLength="100" stroke-dasharray="${part} ${100-part}" stroke-dashoffset="${cur}" transform="rotate(-90 90 90)" opacity="${dim ? .22 : 1}" style="cursor:pointer;transition:.18s"></circle>`; }).join(''); const active = list.find(x=>x.category===selected); const value = active ? active.value : total; return `<svg viewBox="0 0 180 180" width="100%" height="210"><circle cx="90" cy="90" r="67" fill="none" stroke="#eee6d8" stroke-width="24"></circle>${circles}<circle cx="90" cy="90" r="48" fill="#fffaf2"></circle><text x="90" y="82" text-anchor="middle" font-size="11" fill="#7a746b" font-weight="800">${mode==='expense'?'РАСХОДЫ':'ДОХОДЫ'}</text><text x="90" y="103" text-anchor="middle" font-size="18" fill="#171717" font-weight="900">${money(value).replace(/\s?₽/,'')}</text></svg>`; }
  function opsFor(mode, cat){ return state.operations.filter(o=>o.category===cat && o.includeTotals!==false && abs(o.amount)>0.009 && (mode==='income' ? o.direction==='Доход' : ['Расход','Возврат'].includes(o.direction))).sort((a,b)=>String(b.date||'').localeCompare(String(a.date||''))); }
  function drill(mode, cat){ const ops=opsFor(mode,cat); if(!ops.length) return '<div class="empty" style="margin:8px 0 12px">Операций для раскрытия нет</div>'; return `<div style="margin:8px 0 12px;padding:12px;border-radius:20px;background:#fffaf2;box-shadow:0 10px 24px rgba(24,20,15,.08);display:grid;gap:8px">${ops.map(o=>`<button data-edit-op="${esc(o.id)}" style="width:100%;border:0;display:grid;grid-template-columns:58px minmax(0,1fr) auto;gap:9px;align-items:center;padding:10px;border-radius:16px;background:#fff;color:#171717;box-shadow:inset 0 0 0 1px rgba(23,23,23,.08);text-align:left;font:inherit;cursor:pointer"><span style="font-size:12px;color:#7a746b;white-space:nowrap">${showDate(o.date)}</span><span style="min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">${esc(o.description||'Без описания')}</span><b style="white-space:nowrap;color:${num(o.amount)<0?'#b42318':'#087f5b'}">${money(o.amount)}</b></button>`).join('')}</div>`; }
  function categoryList(list, selected, mode, total){ if(!list.length) return '<div class="empty">Нет данных</div>'; return list.map(x=>{ const pct=total?Math.round(x.value/total*100):0, active=(selected===x.category), dim=(selected&&selected!==x.category); const card=`<div data-list-mode="${mode}" data-list-cat="${esc(x.category)}" style="cursor:pointer;margin:8px 0;padding:12px;border-radius:18px;background:${active?'#111':'#fff'};color:${active?'#fff':'#171717'};opacity:${dim ? .55 : 1};box-shadow:${active?'0 12px 28px rgba(17,17,17,.18)':'inset 0 0 0 1px rgba(23,23,23,.08)'};transition:.18s"><div style="display:flex;justify-content:space-between;gap:10px;align-items:center"><span><span style="display:inline-block;width:10px;height:10px;border-radius:50%;background:${x.color};margin-right:8px"></span>${esc(x.category)}</span><b>${money(x.value)}</b></div><div class="bar" style="margin-top:9px;background:${active?'rgba(255,255,255,.22)':'#eee6d8'}"><span style="width:${pct}%;background:${active?'#c8a96a':x.color}"></span></div><div class="small" style="margin-top:5px;color:${active?'rgba(255,255,255,.7)':'#7a746b'}">${pct}%</div></div>`; return card + (active ? drill(mode,x.category) : ''); }).join(''); }
  function bindCharts(){ document.querySelectorAll('[data-chart-cat],[data-list-cat]').forEach(el=>{ el.onclick=()=>{ const mode=el.dataset.chartMode||el.dataset.listMode, cat=el.dataset.chartCat||el.dataset.listCat; if(mode==='expense') selectedExpense = selectedExpense===cat ? null : cat; if(mode==='income') selectedIncome = selectedIncome===cat ? null : cat; renderDashboard(); }; }); document.querySelectorAll('[data-edit-op]').forEach(btn=>{ btn.onclick=ev=>{ ev.stopPropagation(); openEditor(btn.dataset.editOp); }; }); }
  function merchantKey(d){ return clean(d).replace(/\+?\d[\d\s()\-]{5,}/g,' ').replace(/[0-9]+/g,' ').replace(/[.,;:!?"'`~()[\]{}<>/\\|_+=*№#%&^$@]/g,' ').split(' ').filter(w=>w.length>1&&!['оплата','покупка','перевод','платеж','заказ','карта','счет','tinkoff','sber'].includes(w)).slice(0,3).join(' '); }
  function optionHtml(arr, val){ return arr.map(x=>`<option value="${esc(x)}" ${x===val?'selected':''}>${esc(x)}</option>`).join(''); }
  function openEditor(opId){ const op=state.operations.find(x=>String(x.id)===String(opId)); if(!op) return; const key=merchantKey(op.description), count=state.operations.filter(x=>merchantKey(x.description)===key).length; document.querySelectorAll('.bdr-sheet').forEach(x=>x.remove()); const sheet=document.createElement('div'); sheet.className='bdr-sheet'; sheet.style.cssText='position:fixed;inset:auto 0 0 0;z-index:9999;background:#fffaf2;border-radius:28px 28px 0 0;box-shadow:0 -22px 60px rgba(24,20,15,.24);padding:18px;display:grid;gap:12px'; sheet.innerHTML=`<div style="width:42px;height:5px;border-radius:999px;background:#d8cbb8;margin:0 auto 4px"></div><div style="font-weight:950;font-size:18px">Редактировать операцию</div><div style="color:#7a746b;font-size:13px">${showDate(op.date)} · ${esc(op.description||'Без описания')}</div><label style="display:grid;gap:6px;font-size:13px;color:#7a746b">Категория<select id="sheetCat">${optionHtml(cats,op.category)}</select></label><label style="display:grid;gap:6px;font-size:13px;color:#7a746b">Направление<select id="sheetDir">${optionHtml(dirs,op.direction)}</select></label><label style="display:grid;gap:6px;font-size:13px;color:#7a746b">Включать в итоги<select id="sheetInc"><option value="true" ${op.includeTotals!==false?'selected':''}>Да</option><option value="false" ${op.includeTotals===false?'selected':''}>Нет</option></select></label><label style="display:flex;gap:10px;align-items:flex-start;padding:12px;border-radius:18px;background:#fff;box-shadow:inset 0 0 0 1px rgba(23,23,23,.08);font-size:14px"><input id="sheetSimilar" type="checkbox" style="width:auto;margin-top:2px"><span><b>Применить ко всем похожим</b><br><span style="color:#7a746b;font-size:12px">${key?`Шаблон: «${esc(key)}». Найдено: ${count}`:'Похожие операции не найдены'}; будет создано правило.</span></span></label><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px"><button id="sheetCancel">Отмена</button><button id="sheetSave" class="primary">Сохранить</button></div>`; document.body.appendChild(sheet); document.getElementById('sheetCancel').onclick=()=>sheet.remove(); document.getElementById('sheetSave').onclick=()=>{ const cat=document.getElementById('sheetCat').value, dir=document.getElementById('sheetDir').value, inc=document.getElementById('sheetInc').value==='true', sim=document.getElementById('sheetSimilar').checked&&key; let changed=0; if(sim){ state.operations.forEach(x=>{ if(merchantKey(x.description)===key){ x.category=cat; x.direction=dir; x.includeTotals=inc; x.manuallyEdited=true; changed++; } }); if(!state.rules.some(r=>String(r.pattern||'').toLowerCase()===key.toLowerCase())) state.rules.push(rule(key+' → '+cat,'contains',key,cat,dir,inc,95)); } else { op.category=cat; op.direction=dir; op.includeTotals=inc; op.manuallyEdited=true; changed=1; } save(); sheet.remove(); render(); alert(sim?`Сохранено. Обновлено похожих операций: ${changed}. Правило создано.`:'Сохранено'); }; }

  function activate(tab){ activeTab=tab; document.querySelectorAll('.tab,.section').forEach(el=>el.classList.remove('active')); const btn=document.querySelector(`[data-tab="${tab}"]`); if(btn) btn.classList.add('active'); const sec=document.getElementById(tab); if(sec) sec.classList.add('active'); }
  function bindTabs(){ document.querySelectorAll('.tab').forEach(btn=>{ btn.onclick=()=>activate(btn.dataset.tab); }); }
  function render(){ renderDashboard(); renderCurrent(); renderOperations(); renderCredits(); renderManage(); bindTabs(); activate(activeTab); }
  function dashboardSummary(){ const total=summarize(state.operations), ms=months().filter(m=>m!=='Нет данных'), div=ms.length||1; return dashboardMode==='avg' ? {ordinaryIncome:total.ordinaryIncome/div,stableIncome:total.stableIncome/div,routine:total.routine/div,label:'Среднемесячно'} : Object.assign({label:'Итого за период'}, total); }
  function renderDashboard(){ const s=summarize(state.operations), view=dashboardSummary(), available=s.stableIncome-s.routine-s.zhkh-num(state.settings.minSavings), need=Math.max(0,s.routine+s.zhkh+num(state.settings.minSavings)-s.stableIncome), ex=entries(s.byRoutine), et=ex.reduce((z,x)=>z+x.value,0), ii=entries(s.byIncome), it=ii.reduce((z,x)=>z+x.value,0); document.getElementById('dashboard').innerHTML=`<div class="hero"><div class="hero-label">Свободный остаток</div><div class="hero-value">${money(available)}</div><div class="hero-sub"><span class="chip">${state.operations.length} операций</span><span class="chip">Рутина ${money(s.routine)}</span></div></div><div class="card white"><h3>${view.label}</h3><div style="display:flex;gap:6px;background:#f0eadf;border-radius:999px;padding:4px;margin-bottom:12px"><button id="modeTotal" style="padding:8px 10px;box-shadow:none;background:${dashboardMode==='total'?'#111':'transparent'};color:${dashboardMode==='total'?'#fff':'#5e5447'}">Итого</button><button id="modeAvg" style="padding:8px 10px;box-shadow:none;background:${dashboardMode==='avg'?'#111':'transparent'};color:${dashboardMode==='avg'?'#fff':'#5e5447'}">В месяц</button></div><div class="grid"><div><div class="kpi-title">Обычные доходы</div><div class="value">${money(view.ordinaryIncome)}</div></div><div><div class="kpi-title">Стабильные доходы</div><div class="value">${money(view.stableIncome)}</div></div><div><div class="kpi-title">Рутина</div><div class="value">${money(view.routine)}</div></div><div><div class="kpi-title">Нужно сократить</div><div class="value ${need?'bad':'good'}">${money(need)}</div></div></div></div><div class="grid2"><div class="card"><h3>Структура расходов</h3>${pie(ex,selectedExpense,'expense')}<div>${categoryList(ex,selectedExpense,'expense',et)}</div></div><div class="card"><h3>Структура доходов</h3>${pie(ii,selectedIncome,'income')}<div>${categoryList(ii,selectedIncome,'income',it)}</div></div></div>`; document.getElementById('modeTotal').onclick=()=>{dashboardMode='total';localStorage.setItem('bdr.dashboard.mode',dashboardMode);renderDashboard();}; document.getElementById('modeAvg').onclick=()=>{dashboardMode='avg';localStorage.setItem('bdr.dashboard.mode',dashboardMode);renderDashboard();}; bindCharts(); }
  function forecast(m){ const ops=state.operations.filter(o=>o.month===m), f=summarize(ops), days=new Date(+m.slice(0,4),+m.slice(5,7),0).getDate()||30, elapsed=m===new Date().toISOString().slice(0,7)?new Date().getDate():Math.max(1,...ops.map(o=>+String(o.date).slice(8,10)||1)), forecast=elapsed?f.routine/elapsed*days:f.routine, other=months().filter(x=>/^\d{4}-\d{2}$/.test(x)&&x!==m), avg=other.length?other.reduce((z,x)=>z+summarize(state.operations.filter(o=>o.month===x)).routine,0)/other.length:f.routine; return {fact:f,forecast,diffAvg:forecast-avg,elapsed,days}; }
  function renderCurrent(){ const ms=months(), selected=ms.includes(document.getElementById('monthPick')?.value)?document.getElementById('monthPick').value:ms[0], s=summarize(rowsMonth(selected)), f=forecast(selected); document.getElementById('current').innerHTML=`<div class="toolbar"><select id="monthPick">${ms.map(m=>`<option ${m===selected?'selected':''}>${m}</option>`).join('')}</select></div><div class="card white"><h3>Прогноз месяца</h3><div class="grid"><div><div class="kpi-title">Факт рутины</div><div class="value">${money(f.fact.routine)}</div></div><div><div class="kpi-title">Прогноз</div><div class="value">${money(f.forecast)}</div></div><div><div class="kpi-title">Отклонение от среднего</div><div class="value ${f.diffAvg>0?'bad':'good'}">${f.diffAvg>0?'+':''}${money(f.diffAvg)}</div></div><div><div class="kpi-title">Дней</div><div class="value">${f.elapsed}/${f.days}</div></div></div></div><div class="grid"><div class="card"><div class="kpi-title">Доходы</div><div class="value">${money(s.ordinaryIncome)}</div></div><div class="card"><div class="kpi-title">Стабильные</div><div class="value">${money(s.stableIncome)}</div></div><div class="card"><div class="kpi-title">Рутина</div><div class="value">${money(s.routine)}</div></div><div class="card"><div class="kpi-title">ЖКХ</div><div class="value">${money(s.zhkh)}</div></div></div>`; document.getElementById('monthPick').onchange=render; }
  function selectHtml(id, arr, val){ return `<select id="${id}">${arr.map(x=>`<option ${x===val?'selected':''}>${x}</option>`).join('')}</select>`; }
  function cards(ops){ if(!ops.length) return '<div class="empty">Операций нет. Зайди в Управление и примени импорт.</div>'; return `<div style="display:grid;gap:10px">${ops.map(o=>`<div style="background:#fff;border:1px solid rgba(23,23,23,.08);border-radius:22px;padding:14px;box-shadow:0 10px 24px rgba(24,20,15,.06)"><div style="display:flex;justify-content:space-between;gap:12px;align-items:flex-start"><div style="min-width:0"><div class="small muted">${showDate(o.date)} · ${esc(o.bank||'Банк не указан')}</div><div style="font-weight:900;font-size:16px;margin-top:4px;white-space:normal;overflow-wrap:anywhere">${esc(o.description||'Без описания')}</div></div><div style="font-weight:950;font-size:18px;white-space:nowrap;color:${num(o.amount)<0?'#b42318':'#087f5b'}">${money(o.amount)}</div></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:12px"><div>${selectHtml('cat_'+o.id,cats,o.category)}</div><div>${selectHtml('dir_'+o.id,dirs,o.direction)}</div><div>${selectHtml('inc_'+o.id,['Да','Нет'],o.includeTotals?'Да':'Нет')}</div><div><span class="pill">${esc(o.block||'Блок')}</span></div></div></div>`).join('')}</div>`; }
  function renderOperations(){ const rows=filteredOps().slice(0,700); document.getElementById('operations').innerHTML=`<div class="card"><h3>Операции</h3><div class="toolbar"><select id="fMonth"><option value="all">Все месяцы</option>${months().map(m=>`<option>${m}</option>`).join('')}</select><select id="fCat"><option value="all">Все категории</option>${cats.map(c=>`<option>${c}</option>`).join('')}</select><input id="fSearch" placeholder="Поиск по описанию"><button id="fBtn" class="primary">Показать</button></div>${cards(rows)}</div>`; document.getElementById('fBtn').onclick=renderOperations; state.operations.forEach(bindOp); }
  function filteredOps(){ const m=document.getElementById('fMonth')?.value||'all', c=document.getElementById('fCat')?.value||'all', q=clean(document.getElementById('fSearch')?.value||''); return state.operations.filter(o=>(m==='all'||o.month===m)&&(c==='all'||o.category===c)&&(!q||clean(o.description).includes(q))); }
  function bindOp(o){ const cat=document.getElementById('cat_'+o.id), dir=document.getElementById('dir_'+o.id), inc=document.getElementById('inc_'+o.id); if(cat)cat.onchange=()=>{o.category=cat.value;o.manuallyEdited=true;save();render();}; if(dir)dir.onchange=()=>{o.direction=dir.value;o.manuallyEdited=true;save();render();}; if(inc)inc.onchange=()=>{o.includeTotals=inc.value==='Да';o.manuallyEdited=true;save();render();}; }
  function renderCredits(){ const ops=state.operations.filter(o=>credit.includes(o.category)); document.getElementById('credits').innerHTML=`<div class="card"><h3>Кредиты</h3>${table(['Дата','Описание','Сумма'],ops.map(o=>`<tr><td>${showDate(o.date)}</td><td>${esc(o.description)}</td><td>${money(o.amount)}</td></tr>`),'Кредитных операций нет')}</div>`; }
  function renderManage(){ const p=pending?preview(pending):'<p class="muted">После разбора появится предпросмотр. Нажми «Применить импорт», и операции появятся во вкладке «Операции».</p>'; document.getElementById('manage').innerHTML=`<div class="card"><h3>Импорт банков</h3><div class="drop"><b>Выбери 1–3 банковских файла</b><br><br><input id="files" type="file" multiple accept=".xlsx,.xls,.json,.csv,.txt"></div><div class="toolbar"><button id="preview" class="primary">Разобрать файлы</button><button id="apply" ${pending?'':'disabled'}>Применить импорт</button><button id="quick" ${pending?'':'disabled'}>Применить и открыть операции</button></div>${p}</div><div class="card"><h3>Резервная копия</h3><div class="toolbar"><button id="exportDb">Скачать базу JSON</button><button id="clearDb" class="danger">Очистить локальную базу</button></div></div>`; document.getElementById('preview').onclick=async()=>{try{pending=await parseFiles(document.getElementById('files').files);render();}catch(err){alert(err.message||String(err));}}; document.getElementById('apply').onclick=applyImport; document.getElementById('quick').onclick=()=>{applyImport();activate('operations');}; document.getElementById('exportDb').onclick=()=>download('bdr-backup.json',JSON.stringify(state,null,2),'application/json'); document.getElementById('clearDb').onclick=()=>{if(confirm('Очистить локальную базу?')){localStorage.removeItem(STORE);LEGACY.forEach(k=>localStorage.removeItem(k));location.reload();}}; }
  function preview(p){ const s=p.stats; return table(['Показатель','Значение'],[['Файлы',p.files.join(', ')],['Новые операции',s.newRows],['Дубли',s.duplicates],['Исключено',s.excluded],['Требует проверки',s.review],['Доходы',money(s.income)],['Расходы',money(s.expense)],['Кредиты/ипотека',money(s.credits)],['Ипотека справочно',money(s.mortgage)]].map(x=>`<tr><td>${esc(x[0])}</td><td>${esc(x[1])}</td></tr>`)); }
  function applyImport(){ if(!pending) return; state.operations=state.operations.concat(pending.operations); normalizeAll(state); state.imports.push({date:new Date().toISOString(),files:pending.files,count:pending.operations.length}); pending=null; save(); render(); }
  function download(name, content, type){ const blob=new Blob([content],{type}); const link=document.createElement('a'); link.href=URL.createObjectURL(blob); link.download=name; link.click(); URL.revokeObjectURL(link.href); }

  save();
  render();
})();