(() => {
  'use strict';
  const STORE='bdr.money.app.stable.1';
  const LEGACY=['bdr.money.app.v12','bdr.money.app.v11','bdr.money.app.v10','bdr.money.app.v9','bdr.money.app.v8','bdr.money.app.v7','bdr.money.app.v6','bdr.money.app.v5','bdr.money.app.v4','bdr.money.app.v3'];
  const incomeCats=['Зарплата','Стипендия','Проценты и бонусы','Поступления от людей','Пополнение наличными','Прочие доходы','Ипотека/жильё: справочно','Не учитывается'];
  const expenseCats=['Продукты и супермаркеты','Маркетплейсы/покупки','Доставка/Еда вне дома','Транспорт','Связь, интернет, подписки','ЖКХ/квартплата','Здоровье, аптеки и уход','Услуги/комиссии','Страхование','Наличные','Переводы другим людям','Кредиты/ипотека','Ремонт/дом','Крупные разовые расходы','Прочие расходы','Не учитывается'];
  const cats=[...new Set([...incomeCats,...expenseCats])];
  const dirs=['Доход','Расход','Возврат','Справочно','Внутренний перевод','Техническая операция'];
  const stable=['Зарплата','Стипендия','Проценты и бонусы'];
  const incomeReal=['Зарплата','Стипендия','Проценты и бонусы','Поступления от людей','Прочие доходы'];
  const routine=['Продукты и супермаркеты','Маркетплейсы/покупки','Доставка/Еда вне дома','Транспорт','Связь, интернет, подписки','Здоровье, аптеки и уход','Услуги/комиссии','Страхование','Наличные','Ремонт/дом','Прочие расходы'];
  const credit=['Кредиты/ипотека','Ипотека/жильё: справочно'];
  const palette=['#111111','#c8a96a','#6d5b3f','#087f5b','#2454ff','#7c3aed','#b42318','#f59e0b','#475569','#0f766e','#9333ea'];
  let activeTab='dashboard', selectedExpense=null, selectedIncome=null, dashboardMode=localStorage.getItem('bdr.dashboard.mode')||'total', pending=null;
  let state=loadState();
  function uid(){return crypto.randomUUID?crypto.randomUUID():'id_'+Date.now()+'_'+Math.random().toString(16).slice(2)}
  function money(v){return new Intl.NumberFormat('ru-RU',{style:'currency',currency:'RUB',maximumFractionDigits:0}).format(Number(v)||0)}
  function num(v){if(typeof v==='number')return v;if(v==null)return 0;return Number(String(v).replace(/\s| /g,'').replace(',','.').replace(/[₽р]/gi,''))||0}
  function abs(v){return Math.abs(num(v))}
  function clean(v){return String(v??'').toLowerCase().replace(/ё/g,'е').replace(/\s+/g,' ').trim()}
  function esc(v){return String(v??'').replace(/[&<>"]/g,ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[ch]))}
  function asBool(v,def=true){if(v==null||v==='')return def;const s=clean(v);if(['нет','false','0','no'].includes(s))return false;if(['да','true','1','yes'].includes(s))return true;return Boolean(v)}
  function repairDate(v){const s=String(v||'').trim();const m=s.match(/^(\d{4})-(\d{2})-(\d{2})/);if(!m)return s;let y=Number(m[1]);const cur=new Date().getFullYear();if(y!==cur&&['03','04','05','06'].includes(m[2]))y=cur;return `${y}-${m[2]}-${m[3]}`}
  function toDate(v){if(!v)return'';if(v instanceof Date&&!isNaN(v))return repairDate(v.toISOString().slice(0,10));if(typeof v==='number'&&window.XLSX?.SSF?.parse_date_code){const d=XLSX.SSF.parse_date_code(v);if(d)return repairDate(`${d.y}-${String(d.m).padStart(2,'0')}-${String(d.d).padStart(2,'0')}`)}const s=String(v).trim();const m=s.match(/(\d{1,2})[.\/\-](\d{1,2})[.\/\-](\d{2,4})/);if(m){const y=m[3].length===2?'20'+m[3]:m[3];return repairDate(`${y}-${m[2].padStart(2,'0')}-${m[1].padStart(2,'0')}`)}const d=new Date(s);return isNaN(d)?repairDate(s.slice(0,10)):repairDate(d.toISOString().slice(0,10))}
  function showDate(v){const d=toDate(v);const m=d.match(/^(\d{4})-(\d{2})-(\d{2})/);return m?`${m[3]}.${m[2]}.${m[1].slice(2)}`:(d||'—')}
  function monthOf(v){const d=toDate(v);return /^\d{4}-\d{2}/.test(d)?d.slice(0,7):'Без месяца'}
  function baseRules(){return[rule('ПИМУ → Стипендия','contains','пиму','Стипендия','Доход',true,100),rule('Парацельс → Зарплата','contains','парацельс','Зарплата','Доход',true,100),rule('Аквимекс → Зарплата','contains','аквимекс','Зарплата','Доход',true,100),rule('EPR GIS ZKH → ЖКХ','contains','epr_gis_zkh','ЖКХ/квартплата','Расход',true,100),rule('Ипотека → справочно','regex','ипотек|первоначальн|первоначальный взнос|кредитные средства|выдача кредита|зачисление кредита|лицевой счет|эскроу|дду|жилье|жильё|квартира','Ипотека/жильё: справочно','Справочно',false,250)]}
  function rule(name,type,pattern,category,direction,includeTotals,priority=50){return{id:uid(),enabled:true,name,matchType:type,pattern,category,direction,includeTotals,priority}}
  function loadState(){const embedded=Array.isArray(window.operations)?window.operations.map(normalize):[];for(const k of[STORE,...LEGACY]){try{const s=JSON.parse(localStorage.getItem(k));if(s&&Array.isArray(s.operations))return hydrate(s,embedded)}catch(e){}}return hydrate({operations:embedded,rules:baseRules(),imports:[],settings:{minSavings:0}},embedded)}
  function hydrate(s,embedded){s.operations=(s.operations||[]).map(normalize);if(!s.operations.length&&embedded.length)s.operations=embedded;s.rules=(s.rules||baseRules()).map((r,i)=>Object.assign({enabled:true,priority:50+i},r));s.imports=s.imports||[];s.settings=Object.assign({minSavings:0},s.settings||{});normalizeAll(s);return s}
  function save(){localStorage.setItem(STORE,JSON.stringify(state))}
  function normalize(raw){raw=raw||{};const amount=num(raw.amount??raw['Сумма']??raw.sum);const d=toDate(raw.date??raw['Дата']);return{id:raw.id||raw.ID||raw['ID']||uid(),importKey:raw.importKey||'',date:d,month:raw.month||raw['Месяц']||monthOf(d),bank:raw.bank||raw['Банк']||'',sourceType:raw.sourceType||raw['Тип исходный']||raw['Источник']||'',bankCategory:raw.bankCategory||raw['Категория банка']||'',category:raw.category||raw['Категория учета']||raw['Группа БДР']||'Прочие расходы',direction:raw.direction||raw['Направление']||(amount>=0?'Доход':'Расход'),amount,includeTotals:asBool(raw.includeTotals??raw['Учет_БДР']??raw['Включать в общие итоги?'],true),description:raw.description||raw['Описание']||'',account:raw.account||raw['Счет/карта']||raw['Счёт/карта']||'',block:raw.block||raw['Блок учета']||'',manuallyEdited:Boolean(raw.manuallyEdited)}}
  function isMortgage(op){const t=clean([op.description,op.bankCategory,op.sourceType,op.category,op.block,op.account].join(' '));return /ипотек|первоначальн|первоначальный взнос|кредитные средства|выдача кредита|зачисление кредита|лицевой счет|лицевой сч|эскроу|дду|жилье|жильё|квартира/.test(t)||(num(op.amount)>1000000&&/(банк|зачисл|поступл|перевод|кредит)/.test(t))}
  function normalizeAll(s){(s.operations||[]).forEach(op=>{op.date=repairDate(op.date);op.month=monthOf(op.date);if(isMortgage(op)||credit.includes(op.category)){if(isMortgage(op))op.category='Ипотека/жильё: справочно';op.direction=op.category==='Кредиты/ипотека'?'Расход':'Справочно';op.includeTotals=false;op.block='Кредиты'}})}
  function setOp(op,cat,dir,inc,block){op.category=cat;op.direction=dir;op.includeTotals=inc;op.block=block||(!inc?'Исключено':dir==='Доход'?'Доходы':dir==='Справочно'?'Справочно':cat==='ЖКХ/квартплата'?'Обязательные платежи':'Расходы');return op}
  function matchRule(text,r){try{return r.matchType==='regex'?new RegExp(r.pattern,'i').test(text):text.includes(clean(r.pattern))}catch(e){return text.includes(clean(r.pattern))}}
  function classify(op,force=false){if(op.manuallyEdited&&!force)return op;const t=clean([op.description,op.bankCategory,op.sourceType,op.bank,op.account].join(' '));if(isMortgage(op))return setOp(op,'Ипотека/жильё: справочно','Справочно',false,'Кредиты');if(abs(op.amount)===1&&/(магнит|доставка|провер|тест)/.test(t))return setOp(op,'Не учитывается','Техническая операция',false);if(/(сергей к|сергей николаевич|между своими|своей карты|своего счета|пополнение своей|перевод между|сбер.*т.?банк|т.?банк.*сбер)/.test(t))return setOp(op,'Не учитывается','Внутренний перевод',false);const r=state.rules.filter(x=>x.enabled).sort((a,b)=>(b.priority||0)-(a.priority||0)).find(x=>matchRule(t,x));if(r)return setOp(op,r.category,r.direction,r.includeTotals);if(/внесение налич|пополнение налич|банкомат|atm/.test(t))return setOp(op,'Пополнение наличными','Справочно',false);if(/ипотек|погашение кредита|кредит/.test(t)&&op.amount<0)return setOp(op,'Кредиты/ипотека','Расход',false,'Кредиты');if(/возврат|refund|отмена/.test(t)||(op.amount>0&&/расход/.test(clean(op.sourceType))))return setOp(op,mapExpense(t),'Возврат',true);if(op.amount>=0)return setOp(op,mapIncome(t),'Доход',true);return setOp(op,mapExpense(t),'Расход',true)}
  function mapIncome(t){if(/зарплат|аванс/.test(t))return'Зарплата';if(/стипенд|пиму/.test(t))return'Стипендия';if(/кэшбэк|cashback|бонус|процент/.test(t))return'Проценты и бонусы';if(/перевод|зачисление от/.test(t))return'Поступления от людей';return'Прочие доходы'}
  function mapExpense(t){if(/супермаркет|пятероч|магнит|перекресток|ашан|лента|продукт/.test(t))return'Продукты и супермаркеты';if(/wildberries|ozon|маркет|marketplace/.test(t))return'Маркетплейсы/покупки';if(/кафе|ресторан|доставка|еда|delivery|самокат|вкусно|burger|kfc|чио/.test(t))return'Доставка/Еда вне дома';if(/такси|метро|транспорт|автобус|топливо|азс/.test(t))return'Транспорт';if(/мтс|билайн|мегафон|tele2|интернет|подписк|apple|google|yandex plus|кинопоиск/.test(t))return'Связь, интернет, подписки';if(/жкх|квартплат|epr_gis_zkh/.test(t))return'ЖКХ/квартплата';if(/аптек|мед|клиник|стомат|космет|уход/.test(t))return'Здоровье, аптеки и уход';if(/комисс|услуг|сервис/.test(t))return'Услуги/комиссии';if(/страхов/.test(t))return'Страхование';if(/налич|банкомат|atm/.test(t))return'Наличные';if(/перевод/.test(t))return'Переводы другим людям';if(/ремонт|дом|строй|леруа|мебел|hoff/.test(t))return'Ремонт/дом';return'Прочие расходы'}
  function summarize(rows){const s={ordinaryIncome:0,stableIncome:0,routine:0,zhkh:0,large:0,transfers:0,creditInfo:0,mortgageInfo:0,byIncome:{},byRoutine:{}};rows.forEach(op=>{const cat=op.category,a=num(op.amount),aa=abs(a),dir=op.direction;if(credit.includes(cat)){cat==='Кредиты/ипотека'?s.creditInfo+=aa:s.mortgageInfo+=aa;return}if(op.includeTotals===false||cat==='Не учитывается'||aa<=0.009)return;if(dir==='Доход'){if(incomeReal.includes(cat)){s.ordinaryIncome+=a;s.byIncome[cat]=(s.byIncome[cat]||0)+a}if(stable.includes(cat))s.stableIncome+=a}if(dir==='Расход'){if(routine.includes(cat)){s.routine+=aa;s.byRoutine[cat]=(s.byRoutine[cat]||0)+aa}if(cat==='ЖКХ/квартплата')s.zhkh+=aa;if(cat==='Крупные разовые расходы')s.large+=aa;if(cat==='Переводы другим людям')s.transfers+=aa}if(dir==='Возврат'&&routine.includes(cat)){s.routine-=aa;s.byRoutine[cat]=(s.byRoutine[cat]||0)-aa}});return s}
  function months(){const values=[...new Set(state.operations.map(op=>op.month).filter(m=>/^\d{4}-\d{2}$/.test(m)))].sort();return values.length?values:['Нет данных']}
  function rowsMonth(m){return state.operations.filter(op=>m==='all'||op.month===m)}
  function table(headers,rows,empty='Нет данных'){if(!rows.length)return`<div class="empty">${empty}</div>`;return`<div class="scroll"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`}
  function entries(obj){return Object.entries(obj).filter(([,v])=>Number(v)>0.009).sort((a,b)=>b[1]-a[1]).map(([category,value],i)=>({category,value,color:palette[i%palette.length]}))}
  function pie(list,selected,mode){const total=list.reduce((s,x)=>s+x.value,0);if(!total)return'<div class="empty">Нет данных</div>';let off=0;const parts=list.map(x=>{const p=x.value/total*100,sel=selected===x.category,dim=selected&&selected!==x.category,dash=`${p} ${100-p}`,cur=off;off-=p;return`<circle data-chart-mode="${mode}" data-chart-cat="${esc(x.category)}" cx="90" cy="90" r="67" fill="none" stroke="${x.color}" stroke-width="${sel?31:24}" pathLength="100" stroke-dasharray="${dash}" stroke-dashoffset="${cur}" transform="rotate(-90 90 90)" opacity="${dim?.22:1}" style="cursor:pointer;transition:.18s"></circle>`}).join('');const active=list.find(x=>x.category===selected),val=active?active.value:total;return`<svg viewBox="0 0 180 180" width="100%" height="210"><circle cx="90" cy="90" r="67" fill="none" stroke="#eee6d8" stroke-width="24"></circle>${parts}<circle cx="90" cy="90" r="48" fill="#fffaf2"></circle><text x="90" y="82" text-anchor="middle" font-size="11" fill="#7a746b" font-weight="800">${mode==='expense'?'РАСХОДЫ':'ДОХОДЫ'}</text><text x="90" y="103" text-anchor="middle" font-size="18" fill="#171717" font-weight="900">${money(val).replace(/\s?₽/,'')}</text></svg>`}
  function opsFor(mode,cat){return state.operations.filter(op=>op.category===cat&&op.includeTotals!==false&&abs(op.amount)>0.009&&(mode==='income'?op.direction==='Доход':['Расход','Возврат'].includes(op.direction))).sort((a,b)=>String(b.date||'').localeCompare(String(a.date||'')))}
  function drill(mode,cat){const ops=opsFor(mode,cat);if(!ops.length)return'<div class="empty" style="margin:8px 0 12px">Операций нет</div>';return`<div style="margin:8px 0 12px;padding:12px;border-radius:20px;background:#fffaf2;box-shadow:0 10px 24px rgba(24,20,15,.08);display:grid;gap:8px">${ops.map(op=>`<button data-edit-op="${esc(op.id)}" style="width:100%;border:0;display:grid;grid-template-columns:58px minmax(0,1fr) auto;gap:9px;align-items:center;padding:10px;border-radius:16px;background:#fff;color:#171717;box-shadow:inset 0 0 0 1px rgba(23,23,23,.08);text-align:left;font:inherit;cursor:pointer"><span style="font-size:12px;color:#7a746b;white-space:nowrap">${showDate(op.date)}</span><span style="min-width:0;overflow:hidden;text-overflow:ellipsis;white-space:nowrap">${esc(op.description||'Без описания')}</span><b style="white-space:nowrap;color:${num(op.amount)<0?'#b42318':'#087f5b'}">${money(op.amount)}</b></button>`).join('')}</div>`}
  function catList(list,selected,mode,total){if(!list.length)return'<div class="empty">Нет данных</div>';return list.map(x=>{const pct=total?Math.round(x.value/total*100):0,active=selected===x.category,dim=selected&&selected!==x.category;return`<div data-list-mode="${mode}" data-list-cat="${esc(x.category)}" style="cursor:pointer;margin:8px 0;padding:12px;border-radius:18px;background:${active?'#111':'#fff'};color:${active?'#fff':'#171717'};opacity:${dim?.55:1};box-shadow:${active?'0 12px 28px rgba(17,17,17,.18)':'inset 0 0 0 1px rgba(23,23,23,.08)'};transition:.18s"><div style="display:flex;justify-content:space-between;gap:10px;align-items:center"><span><span style="display:inline-block;width:10px;height:10px;border-radius:50%;background:${x.color};margin-right:8px"></span>${esc(x.category)}</span><b>${money(x.value)}</b></div><div class="bar" style="margin-top:9px;background:${active?'rgba(255,255,255,.22)':'#eee6d8'}"><span style="width:${pct}%;background:${active?'#c8a96a':x.color}"></span></div><div class="small" style="margin-top:5px;color:${active?'rgba(255,255,255,.7)':'#7a746b'}">${pct}%</div></div>${active?drill(mode,x.category):''}`}).join('')}
  function bindCharts(){document.querySelectorAll('[data-chart-cat],[data-list-cat]').forEach(el=>{el.onclick=()=>{const mode=el.dataset.chartMode||el.dataset.listMode,cat=el.dataset.chartCat||el.dataset.listCat;if(mode==='expense')selectedExpense=selectedExpense===cat?null:cat;if(mode==='income')selectedIncome=selectedIncome===cat?null:cat;renderDashboard()}});document.querySelectorAll('[data-edit-op]').forEach(b=>b.onclick=e=>{e.stopPropagation();openEditor(b.dataset.editOp)})}
  function merchantKey(desc){return clean(desc).replace(/\+?\d[\d\s()\-]{5,}/g,' ').replace(/[0-9]+/g,' ').replace(/[.,;:!?"'`~()[\]{}<>/\\|_+=*№#%&^$@]/g,' ').split(' ').filter(w=>w.length>1&&!['оплата','покупка','перевод','платеж','заказ','карта','счет'].includes(w)).slice(0,3).join(' ')}
  function options(values,selected){return values.map(v=>`<option ${v===selected?'selected':''}>${esc(v)}</option>`).join('')}
  function openEditor(id){const op=state.operations.find(x=>String(x.id)===String(id));if(!op)return;const key=merchantKey(op.description),similar=state.operations.filter(x=>merchantKey(x.description)===key).length;document.querySelectorAll('.bdr-sheet').forEach(x=>x.remove());const sheet=document.createElement('div');sheet.className='bdr-sheet';sheet.style.cssText='position:fixed;inset:auto 0 0 0;z-index:9999;background:#fffaf2;border-radius:28px 28px 0 0;box-shadow:0 -22px 60px rgba(24,20,15,.24);padding:18px;display:grid;gap:12px';sheet.innerHTML=`<div style="width:42px;height:5px;border-radius:999px;background:#d8cbb8;margin:0 auto 4px"></div><div style="font-weight:950;font-size:18px">Редактировать операцию</div><div style="color:#7a746b;font-size:13px">${showDate(op.date)} · ${esc(op.description)}</div><label style="display:grid;gap:6px;font-size:13px;color:#7a746b">Категория<select id="sheetCat">${options(cats,op.category)}</select></label><label style="display:grid;gap:6px;font-size:13px;color:#7a746b">Направление<select id="sheetDir">${options(dirs,op.direction)}</select></label><label style="display:grid;gap:6px;font-size:13px;color:#7a746b">Включать в итоги<select id="sheetInc"><option value="true" ${op.includeTotals!==false?'selected':''}>Да</option><option value="false" ${op.includeTotals===false?'selected':''}>Нет</option></select></label><label style="display:flex;gap:10px;align-items:flex-start;padding:12px;border-radius:18px;background:#fff;box-shadow:inset 0 0 0 1px rgba(23,23,23,.08);font-size:14px"><input id="sheetSimilar" type="checkbox" style="width:auto;margin-top:2px"><span><b>Применить ко всем похожим</b><br><span style="color:#7a746b;font-size:12px">${key?`Шаблон: «${esc(key)}». Найдено: ${similar}`:'Похожие операции не найдены'}; будет создано правило.</span></span></label><div style="display:grid;grid-template-columns:1fr 1fr;gap:10px"><button id="cancelEdit">Отмена</button><button id="saveEdit" class="primary">Сохранить</button></div>`;document.body.appendChild(sheet);document.getElementById('cancelEdit').onclick=()=>sheet.remove();document.getElementById('saveEdit').onclick=()=>{const cat=document.getElementById('sheetCat').value,dir=document.getElementById('sheetDir').value,inc=document.getElementById('sheetInc').value==='true',apply=document.getElementById('sheetSimilar').checked&&key;let changed=0;if(apply){state.operations.forEach(x=>{if(merchantKey(x.description)===key){x.category=cat;x.direction=dir;x.includeTotals=inc;x.manuallyEdited=true;changed++}});if(!state.rules.some(r=>String(r.pattern||'').toLowerCase()===key.toLowerCase()))state.rules.push(rule(`${key} → ${cat}`,'contains',key,cat,dir,inc,95))}else{op.category=cat;op.direction=dir;op.includeTotals=inc;op.manuallyEdited=true;changed=1}save();sheet.remove();render();alert(apply?`Сохранено. Обновлено похожих операций: ${changed}. Правило создано.`:'Сохранено')}}
  function activate(tab){activeTab=tab;document.querySelectorAll('.tab,.section').forEach(el=>el.classList.remove('active'));document.querySelector(`[data-tab="${tab}"]`)?.classList.add('active');document.getElementById(tab)?.classList.add('active')}
  function bindTabs(){document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>activate(b.dataset.tab))}
  function render(){renderDashboard();renderCurrent();renderOperations();renderCredits();renderManage();bindTabs();activate(activeTab)}
  function renderDashboard(){const s=summarize(state.operations),ms=months().filter(m=>m!=='Нет данных'),div=ms.length||1,view=dashboardMode==='avg'?{ordinaryIncome:s.ordinaryIncome/div,stableIncome:s.stableIncome/div,routine:s.routine/div,label:'Среднемесячно'}:{ordinaryIncome:s.ordinaryIncome,stableIncome:s.stableIncome,routine:s.routine,label:'Итого за период'},exp=entries(s.byRoutine),inc=entries(s.byIncome),et=exp.reduce((a,b)=>a+b.value,0),it=inc.reduce((a,b)=>a+b.value,0);document.getElementById('dashboard').innerHTML=`<div class="hero"><div class="hero-label">Свободный остаток</div><div class="hero-value">${money(s.stableIncome-s.routine-s.zhkh)}</div><div class="hero-sub"><span class="chip">${state.operations.length} операций</span><span class="chip">Рутина ${money(s.routine)}</span></div></div><div class="card white"><h3>${view.label}</h3><div style="display:flex;gap:6px;background:#f0eadf;border-radius:999px;padding:4px;margin-bottom:12px"><button id="modeTotal" style="padding:8px 10px;box-shadow:none;background:${dashboardMode==='total'?'#111':'transparent'};color:${dashboardMode==='total'?'#fff':'#5e5447'}">Итого</button><button id="modeAvg" style="padding:8px 10px;box-shadow:none;background:${dashboardMode==='avg'?'#111':'transparent'};color:${dashboardMode==='avg'?'#fff':'#5e5447'}">В месяц</button></div><div class="grid"><div><div class="kpi-title">Обычные доходы</div><div class="value">${money(view.ordinaryIncome)}</div></div><div><div class="kpi-title">Стабильные доходы</div><div class="value">${money(view.stableIncome)}</div></div><div><div class="kpi-title">Рутина</div><div class="value">${money(view.routine)}</div></div><div><div class="kpi-title">Остаток</div><div class="value">${money(view.stableIncome-view.routine)}</div></div></div></div><div class="grid2"><div class="card"><h3>Структура расходов</h3>${pie(exp,selectedExpense,'expense')}<div>${catList(exp,selectedExpense,'expense',et)}</div></div><div class="card"><h3>Структура доходов</h3>${pie(inc,selectedIncome,'income')}<div>${catList(inc,selectedIncome,'income',it)}</div></div></div>`;document.getElementById('modeTotal').onclick=()=>{dashboardMode='total';localStorage.setItem('bdr.dashboard.mode',dashboardMode);renderDashboard()};document.getElementById('modeAvg').onclick=()=>{dashboardMode='avg';localStorage.setItem('bdr.dashboard.mode',dashboardMode);renderDashboard()};bindCharts()}
  function currentForecast(m){const monthOps=state.operations.filter(op=>op.month===m),fact=summarize(monthOps),days=new Date(Number(m.slice(0,4)),Number(m.slice(5,7)),0).getDate()||30,maxDay=Math.max(1,...monthOps.map(op=>Number(String(op.date).slice(8,10))||1)),elapsed=m===new Date().toISOString().slice(0,7)?new Date().getDate():maxDay,forecast=elapsed?fact.routine/elapsed*days:fact.routine,other=months().filter(x=>/^\d{4}-\d{2}$/.test(x)&&x!==m),avg=other.length?other.reduce((sum,x)=>sum+summarize(state.operations.filter(op=>op.month===x)).routine,0)/other.length:fact.routine;return{fact,forecast,avg,diff:forecast-avg,elapsed,days}}
  function renderCurrent(){const ms=months(),selected=ms.includes(document.getElementById('monthPick')?.value)?document.getElementById('monthPick').value:ms[0],s=summarize(rowsMonth(selected)),f=currentForecast(selected);document.getElementById('current').innerHTML=`<div class="toolbar"><select id="monthPick">${ms.map(m=>`<option ${m===selected?'selected':''}>${m}</option>`).join('')}</select></div><div class="card white"><h3>Прогноз месяца</h3><div class="grid"><div><div class="kpi-title">Факт рутины</div><div class="value">${money(f.fact.routine)}</div></div><div><div class="kpi-title">Прогноз</div><div class="value">${money(f.forecast)}</div></div><div><div class="kpi-title">Отклонение от среднего</div><div class="value ${f.diff>0?'bad':'good'}">${f.diff>0?'+':''}${money(f.diff)}</div></div><div><div class="kpi-title">Дней</div><div class="value">${f.elapsed}/${f.days}</div></div></div></div><div class="grid"><div class="card"><div class="kpi-title">Доходы</div><div class="value">${money(s.ordinaryIncome)}</div></div><div class="card"><div class="kpi-title">Стабильные</div><div class="value">${money(s.stableIncome)}</div></div><div class="card"><div class="kpi-title">Рутина</div><div class="value">${money(s.routine)}</div></div><div class="card"><div class="kpi-title">ЖКХ</div><div class="value">${money(s.zhkh)}</div></div></div>`;document.getElementById('monthPick').onchange=render}
  function opCards(ops){if(!ops.length)return'<div class="empty">Операций нет.</div>';return`<div style="display:grid;gap:10px">${ops.map(op=>`<div style="background:#fff;border:1px solid rgba(23,23,23,.08);border-radius:22px;padding:14px;box-shadow:0 10px 24px rgba(24,20,15,.06)"><div style="display:flex;justify-content:space-between;gap:12px;align-items:flex-start"><div><div class="small muted">${showDate(op.date)} · ${esc(op.bank||'Банк не указан')}</div><div style="font-weight:900;font-size:16px;margin-top:4px">${esc(op.description||'Без описания')}</div></div><div style="font-weight:950;font-size:18px;white-space:nowrap;color:${num(op.amount)<0?'#b42318':'#087f5b'}">${money(op.amount)}</div></div><div style="display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:12px"><div>${selectHtml('cat_'+op.id,cats,op.category)}</div><div>${selectHtml('dir_'+op.id,dirs,op.direction)}</div><div>${selectHtml('inc_'+op.id,['Да','Нет'],op.includeTotals?'Да':'Нет')}</div><div><span class="pill">${esc(op.block||'Блок')}</span></div></div></div>`).join('')}</div>`}
  function renderOperations(){const rows=filteredOps().slice(0,700);document.getElementById('operations').innerHTML=`<div class="card"><h3>Операции</h3><div class="toolbar"><select id="fMonth"><option value="all">Все месяцы</option>${months().map(m=>`<option>${m}</option>`).join('')}</select><select id="fCat"><option value="all">Все категории</option>${cats.map(c=>`<option>${c}</option>`).join('')}</select><input id="fSearch" placeholder="Поиск"><button id="fBtn" class="primary">Показать</button></div>${opCards(rows)}</div>`;document.getElementById('fBtn').onclick=renderOperations;state.operations.forEach(bindOp)}
  function filteredOps(){const m=document.getElementById('fMonth')?.value||'all',c=document.getElementById('fCat')?.value||'all',q=clean(document.getElementById('fSearch')?.value||'');return state.operations.filter(op=>(m==='all'||op.month===m)&&(c==='all'||op.category===c)&&(!q||clean(op.description).includes(q)))}
  function selectHtml(id,values,value){return`<select id="${id}">${values.map(v=>`<option ${v===value?'selected':''}>${v}</option>`).join('')}</select>`}
  function bindOp(op){const cat=document.getElementById('cat_'+op.id),dir=document.getElementById('dir_'+op.id),inc=document.getElementById('inc_'+op.id);if(cat)cat.onchange=()=>{op.category=cat.value;op.manuallyEdited=true;save();render()};if(dir)dir.onchange=()=>{op.direction=dir.value;op.manuallyEdited=true;save();render()};if(inc)inc.onchange=()=>{op.includeTotals=inc.value==='Да';op.manuallyEdited=true;save();render()}}
  function renderCredits(){const ops=state.operations.filter(op=>credit.includes(op.category));document.getElementById('credits').innerHTML=`<div class="card"><h3>Кредиты</h3>${table(['Дата','Описание','Сумма'],ops.map(op=>`<tr><td>${showDate(op.date)}</td><td>${esc(op.description)}</td><td>${money(op.amount)}</td></tr>`),'Кредитных операций нет')}</div>`}
  function renderManage(){const preview=pending?renderPreview(pending):'<p class="muted">После разбора появится предпросмотр.</p>';document.getElementById('manage').innerHTML=`<div class="card"><h3>Импорт банков</h3><div class="drop"><b>Выбери банковские файлы</b><br><br><input id="files" type="file" multiple accept=".xlsx,.xls,.json,.csv,.js,.txt"></div><div class="toolbar"><button id="preview" class="primary">Разобрать файлы</button><button id="apply" ${pending?'':'disabled'}>Применить импорт</button><button id="quick" ${pending?'':'disabled'}>Применить и открыть операции</button></div>${preview}</div><div class="card"><h3>Правила категоризации</h3>${ruleForm()}${rulesTable()}</div><div class="card"><h3>Резервная копия</h3><div class="toolbar"><button id="exportDb">Скачать базу JSON</button><button id="clearDb" class="danger">Очистить локальную базу</button></div></div>`;document.getElementById('preview').onclick=async()=>{try{pending=await parseFiles(document.getElementById('files').files);render()}catch(e){alert(e.message||String(e))}};document.getElementById('apply').onclick=applyImport;document.getElementById('quick').onclick=()=>{applyImport();activate('operations')};document.getElementById('addRule').onclick=addRule;document.getElementById('exportDb').onclick=()=>download('bdr-backup.json',JSON.stringify(state,null,2),'application/json');document.getElementById('clearDb').onclick=()=>{if(confirm('Очистить базу?')){localStorage.removeItem(STORE);LEGACY.forEach(k=>localStorage.removeItem(k));location.reload()}};state.rules.forEach(r=>{const b=document.getElementById('del_'+r.id);if(b)b.onclick=()=>{state.rules=state.rules.filter(x=>x.id!==r.id);save();render()}})}
  function renderPreview(p){const s=p.stats;return table(['Показатель','Значение'],[['Файлы',p.files.join(', ')],['Новые операции',s.newRows],['Дубли',s.duplicates],['Исключено',s.excluded],['Доходы',money(s.income)],['Расходы',money(s.expense)]].map(([a,b])=>`<tr><td>${esc(a)}</td><td>${esc(b)}</td></tr>`))}
  function applyImport(){if(!pending)return;state.operations=state.operations.concat(pending.operations);normalizeAll(state);state.imports.push({date:new Date().toISOString(),files:pending.files,count:pending.operations.length});pending=null;save();render()}
  async function parseFiles(files){if(!files||!files.length)throw new Error('Сначала выбери файл.');let rows=[];for(const f of files)rows=rows.concat(await parseFile(f));rows=rows.map(o=>classify(o));const existing=new Set(state.operations.map(o=>o.importKey||key(o)));const seen=new Set();let dup=0;const fresh=[];for(const o of rows){o.importKey=key(o);if(existing.has(o.importKey)||seen.has(o.importKey))dup++;else{seen.add(o.importKey);fresh.push(o)}}const s=summarize(fresh);return{files:[...files].map(f=>f.name),operations:fresh,duplicates:dup,stats:{newRows:fresh.length,duplicates:dup,excluded:fresh.filter(o=>!o.includeTotals).length,income:s.ordinaryIncome,expense:s.routine+s.zhkh}}}
  async function parseFile(file){const name=file.name.toLowerCase();if(name.endsWith('.json'))return JSON.parse(await file.text()).map(normalize);if(name.endsWith('.csv')||name.endsWith('.txt'))return parseCsv(await file.text(),name);if(!window.XLSX)throw new Error('Не загрузилась XLSX-библиотека.');const wb=XLSX.read(await file.arrayBuffer(),{type:'array',cellDates:true});let out=[];wb.SheetNames.forEach(sn=>{const rows=XLSX.utils.sheet_to_json(wb.Sheets[sn],{header:1,raw:false,defval:''});out=out.concat(parseSheet(rows,name))});return out}
  function parseCsv(text,name){const sep=text.includes(';')?';':text.includes('\t')?'\t':',';const lines=text.split(/\r?\n/).filter(Boolean);const h=split(lines.shift(),sep);return lines.map(l=>rowToOp(Object.fromEntries(split(l,sep).map((v,i)=>[h[i]||'col'+i,v])),name)).filter(Boolean)}
  function split(line,sep){const out=[];let cur='',q=false;for(const ch of line){if(ch==='"'){q=!q;continue}if(ch===sep&&!q){out.push(cur);cur='';continue}cur+=ch}out.push(cur);return out}
  function parseSheet(rows,name){const idx=rows.findIndex(r=>{const t=clean(r.join(' '));return r.filter(Boolean).length>=3&&['дата','сумма','описан','операц','назнач','категор','карта','счет','счёт'].filter(w=>t.includes(w)).length>=2});if(idx<0)return[];const h=rows[idx].map(x=>String(x).trim());return rows.slice(idx+1).map(r=>rowToOp(Object.fromEntries(h.map((k,i)=>[k,r[i]])),name)).filter(Boolean)}
  function val(o,names){const e=Object.entries(o);for(const n of names){const f=e.find(([k])=>clean(k)===clean(n)||clean(k).includes(clean(n)));if(f)return f[1]}return''}
  function rowToOp(o,name){const bank=/сбер|sber/.test(name)?'Сбер':/тбанк|тинькофф|tinkoff|t-bank/.test(name)?'Т-Банк':val(o,['Банк']);const sourceType=/доход/.test(name)?'Доходы файл':/расход/.test(name)?'Расходы файл':val(o,['Источник'])||'Банковская выгрузка';const date=toDate(val(o,['Дата','Дата операции','Дата платежа','Дата и время','date']));const desc=String(val(o,['Описание','Назначение платежа','Операция','Детали операции','Контрагент','Получатель','Плательщик','Место операции','description'])||'').trim();let amount=num(val(o,['Сумма','Сумма операции','Сумма платежа','amount','Приход','Расход']));const inc=num(val(o,['Приход','Зачисления','Поступления'])),exp=num(val(o,['Расход','Списания']));if(inc)amount=Math.abs(inc);if(exp)amount=-Math.abs(exp);if(/расход/.test(name)&&amount>0)amount=-Math.abs(amount);if(/доход/.test(name)&&amount<0)amount=Math.abs(amount);if(!date&&!desc&&!amount)return null;return normalize({date,bank,sourceType,bankCategory:val(o,['Категория','Категория банка']),amount,description:desc,account:val(o,['Счет','Счёт','Карта','Счет/карта','Счёт/карта'])})}
  function key(o){return[o.date,Math.round(num(o.amount)*100)/100,clean(o.bank),clean(o.description),clean(o.account),clean(o.sourceType)].join('|')}
  function ruleForm(){return`<div class="rule-card"><div class="toolbar"><input id="rName" placeholder="Название"><select id="rType"><option value="contains">Текст содержит</option><option value="regex">Регулярное выражение</option></select><input id="rPattern" placeholder="Например: Чио Чио"><select id="rCat">${cats.map(c=>`<option>${c}</option>`).join('')}</select><select id="rDir">${dirs.map(d=>`<option>${d}</option>`).join('')}</select><select id="rInc"><option value="true">Включать</option><option value="false">Не учитывать</option></select><button id="addRule" class="primary">Создать правило</button></div></div>`}
  function addRule(){state.rules.push(rule(document.getElementById('rName').value||document.getElementById('rPattern').value,document.getElementById('rType').value,document.getElementById('rPattern').value,document.getElementById('rCat').value,document.getElementById('rDir').value,document.getElementById('rInc').value==='true',80));save();render()}
  function rulesTable(){return table(['Название','Условие','Категория','Направление',''],state.rules.map(r=>`<tr><td>${esc(r.name)}</td><td>${esc(r.matchType)}: ${esc(r.pattern)}</td><td>${esc(r.category)}</td><td>${esc(r.direction)}</td><td><button id="del_${r.id}" class="danger">Удалить</button></td></tr>`),'Правил нет')}
  function download(name,content,type){const blob=new Blob([content],{type});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();URL.revokeObjectURL(a.href)}
  save();render();
})();